name: deployment binarie to s3

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-2022

        steps:
          - uses: actions/checkout@v4
          - uses: actions/cache@v4
            with:
              path: |
                ~/.cache/pip
                ~/.platformio/.cache
              key: ${{ runner.os }}-pio
          - uses: actions/setup-python@v5
            with:
              python-version: '3.11'
          - name: Install PlatformIO Core
            run: pip install --upgrade platformio
    
          - name: Build PlatformIO Project
            run: pio run
    
          - name: Find and Save Binary
            id: find-binary
            shell: cmd
            run: |
              FOR /F "delims=" %%F IN ('dir /b /s .pio\build\esp32dev\firmware.bin') DO SET BINARY_FILE=%%F
              echo Binary file path: %BINARY_FILE%
              echo ::set-output name=binary_path::%BINARY_FILE%
            
          - name: Install AWS CLI
            shell: powershell
            run: |
              msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi
            
          - name: Configure AWS CLI
            shell: cmd
            run: |
              aws configure set aws_access_key_id %AWS_ACCESS_KEY_ID%
              aws configure set aws_secret_access_key %AWS_SECRET_ACCESS_KEY%
              aws configure set default.region us-east-1
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
          - name: Upload binary to S3 with specific name
            if: success()
            shell: cmd
            run: |
              aws s3 cp D:\a\ESP32RemoteIO\ESP32RemoteIO\.pio\build\esp32dev\firmware.bin s3://%AWS_S3_BUCKET%/%PATH%/firmwareESP32.bin --acl public-read
            env:
              PATH: ${{ secrets.PATH }}
              AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
